{
	"version": 1768369838,
	"fileList": [
		"data.js",
		"c2runtime.js",
		"jquery-3.4.1.min.js",
		"offlineClient.js",
		"images/player2-sheet0.png",
		"images/obj_floor-sheet0.png",
		"images/sprite-sheet0.png",
		"images/golditem-sheet0.png",
		"images/sprite2-sheet0.png",
		"images/obj_turret-sheet0.png",
		"images/obj_bullet-sheet0.png",
		"images/obj_bg1-sheet0.png",
		"images/obj_green-sheet0.png",
		"images/sprite3-sheet0.png",
		"images/obg_red-sheet0.png",
		"images/btn_mute-sheet0.png",
		"images/btn_mute-sheet1.png",
		"media/ogg  coin-upaif-14631.ogg",
		"media/ogg  geme_retro_jump_2-206573.ogg",
		"media/pew_pew-dknight556-1379997159.ogg",
		"media/phmkh-othskhrabphii.ogg",
		"media/recording-_3_.ogg",
		"media/untitled_y2fyhgt.ogg",
		"icon-16.png",
		"icon-32.png",
		"icon-114.png",
		"icon-128.png",
		"icon-256.png",
		"loading-logo.png"
	]
}